image:
  file: Dockerfile


ports:
  - port: 5000
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore
  - port: 5044
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 8800
    onOpen: ignore
  - port: 587
    onOpen: ignore
  - port: 22300
    onOpen: open-preview
vscode:
  extensions:
    - ms-azuretools.vscode-docker
