# This compose file can be used in development to run both the database and app within Docker.

version: '3.7'

services:

    db:
        image: postgres:13
        ports:
            - "5432:5432"
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=joplin_db_1
            - POSTGRES_HOST_AUTH_METHOD=trust
    app:
        image: joplin/server:latest
        depends_on: 
            - db
        ports:
            - "8808:8808"
        environment:
            - DB_CLIENT=pg
            - POSTGRES_DATABASE=joplin_db_1
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=localhost
