# This compose file can be used in development to run both the database and app within Docker.

version: '3.7'

services:
    db:
        image: postgres:13
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=worthATry
            - POSTGRES_USER=worthATry
            - POSTGRES_DB=joplin_db_1


    app:
        image:
        file: docker/Dockerfile
        depends_on: 
            - db
        ports:
            - "22300:22300"
        environment:
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=worthATry
            - POSTGRES_DATABASE=joplin_db_1
            - POSTGRES_USER=worthATry
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=localhost
        extra_hosts:
        - "host.docker.internal:172.18.0.1"
